# Damian Rudnik WAGO 01.2021
# Running Influx with Grafana
# PIf you want to save data to SD Card change volumes to: /media/sd/influxdata:/var/lib/influxdb and /media/sd/grafana:/var/lib/grafana:rw 
# In Grafana you should select "Skip TLS Verify" and "Basic Auth".
# Default passwords are admin/wago, you can change it
version: '3.5'
services:
  database:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    volumes:
      - /home/influxdata:/var/lib/influxdb
    ports:
     - '8086:8086'
    networks:
     - pfcnet
    environment:
     # activates the access via udp
     - INFLUXDB_DB=db
     - INFLUXDB_USER=user
     - INFLUXDB_USER_PASSWORD=wago
     # deactivates statistics to  usage.influxdata.com
     - INFLUXDB_REPORTING_DISABLED=true
     - INFLUXDB_ADMIN_ENABLED=true
     - INFLUXDB_ADMIN_USER=admin
     - INFLUXDB_ADMIN_PASSWORD=wago

  grafana:
    image: grafana/grafana
    user: "0"
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    networks:
      - pfcnet
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/grafana:/var/lib/grafana:rw   
    depends_on:
      - database
networks:
  pfcnet:
